tasks: # list of tasks

  # use plain R scripts
  - source: raw.R # write iris data to CSV
    product:
      # this is the executed version of your script
      # you can review tables and charts here
      nb: output/raw.ipynb # output notebook can also be html
      data: output/raw.csv

  - source: clean.R # clean iris data
    product:
      nb: output/clean.ipynb # output notebook can also be html
      data: output/clean.csv # cleaned data

  # R markdown files also supported
  - source: plot.Rmd # plot iris data
    product: 
      nb: output/plot.ipynb

  # Quarto does not work yet :(
  # - source: plot2.Qmd
  #   product: 
  #     nb: output/quarto.ipynb
