name: cookbook-grid

channels:
  - conda-forge

dependencies:
  - python=3.10
  - r-base=4.0.3 # install R
  - r-irkernel # install R kernel for Jupyter
  - pip
  - pip:
    - ploomber
    - pandas
    - scikit-learn

